# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

bfs_propagate_cpp <- function(n_cells, neighbors, cell_friction_raw, seed_cells, starter_cells_list, barrier_mat, subdiv_mat, subdiv_penalty, base_step_fric, use_pop, cell_pop, target_pop, pop_sat_pct, pop_sat_weight, pop_sat_max, n_areas) {
    .Call(`_bfsprop_bfs_propagate_cpp`, n_cells, neighbors, cell_friction_raw, seed_cells, starter_cells_list, barrier_mat, subdiv_mat, subdiv_penalty, base_step_fric, use_pop, cell_pop, target_pop, pop_sat_pct, pop_sat_weight, pop_sat_max, n_areas)
}
